AppBundle\Entity\techSubTasks:
    type: entity
    table: t_tech_sub_tasks
    manyToOne:
      subTasksByTasks:
        targetEntity: techTasks
        inversedBy: tasksBySubTasks
        joinColumn:
            name: taskId
            referencedColumnName: id
    repositoryClass: AppBundle\Repository\techSubTasksRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    lifecycleCallbacks: {  }
    fields:
      description:
          type: string
      active:
          type: boolean
          option:
            defaults: 0
      checked:
          type: boolean
          option:
            defaults: 0
