AppBundle\Entity\techUsers:
    type: entity
    table: t_tech_users
    oneToMany:
        tasksByUsers:
              targetEntity: techTasksByUsers
              mappedBy: usersByTasks
        projectsByUsers:
              targetEntity: techProjectsByUsers
              mappedBy: usersByProjects
        usersProjects:
              targetEntity: techProjects
              mappedBy: projectsUsers
    repositoryClass: AppBundle\Repository\techUsersRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    lifecycleCallbacks:
        prePersist: [ insertCreatedAtAuto, insertUpdateAtAuto ]
    fields:
      username:
          type: string
      email:
          type: string
      password:
          type: string
      picture:
          type: text
          length: 4294967295
      active:
          type: boolean
          option:
            defaults: 0
      personalKey:
          type: string
      createdAt:
          type: datetime
      updatedAt:
          type: datetime
