AppBundle\Entity\techCategories:
    type: entity
    table: t_tech_categories
    oneToMany:
        categoriesByTasks:
              targetEntity: techTasks
              mappedBy: tasksByCategories
    manyToOne:
      projectsByCategories:
        targetEntity: techProjects
        inversedBy: categoriesByProjects
        joinColumn:
            name: projectId
            referencedColumnName: id
    repositoryClass: AppBundle\Repository\techCategoriesRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    lifecycleCallbacks: {  }
    fields:
      name:
          type: string