AppBundle\Entity\techTasks:
    type: entity
    table: t_tech_tasks
    oneToMany:
        usersInTasksByTasks:
              targetEntity: techTasksByUsers
              mappedBy: tasksByTasksInUsers
        tasksBySubTasks:
              targetEntity: techSubTasks
              mappedBy: subTasksByTasks
    manyToOne:
      tasksByCategories:
        targetEntity: techCategories
        inversedBy: categoriesByTasks
        joinColumn:
            name: categId
            referencedColumnName: id
    repositoryClass: AppBundle\Repository\techTasksRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    lifecycleCallbacks: {  }
    fields:
      name:
          type: string