login:
  path: /authentification/profiles
  defaults:  { _controller: AppBundle:Profile:authentificationProfiles }

register:
  path: /add/profiles
  defaults:  { _controller: AppBundle:Profile:addProfiles }